CC         =  mpicc
CCFLAGS    =  -O3
LIBS       =  -lm

A2 :A2.c
	$(CC) $(CCFLAGS)  -o A2 A2.c $(LIBS)

A2a :A2a.c
	$(CC) $(CCFLAGS)  -o A2a A2a.c $(LIBS)



try :try.c
	$(CC) $(CCFLAGS)  -o try try.c $(LIBS)

clean:
	rm -f A2 *~
